FROM ubuntu:20.04

MAINTAINER erudshtein

ENV DEBIAN_FRONTEND=noninteractive

RUN apt -qq update \
    && apt -qq -y install curl bzip2 nano \
    && curl -sSL https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -bfp /usr/local \
    && conda install -y ubuntu=3 \
    && conda update conda \
    && conda config --set channel_priority strict \
    && conda config --remove channels defaults \
    && conda config --add channels anaconda \
    && conda config --append channels conda-forge \
    && conda clean --all --yes \
    && apt -qq -y autoremove \
    && apt autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log \
    && rm -rf /tmp/miniconda.sh

RUN conda init bash
