version: "3.9"

services:

  cassandra-master:
    image: cassandra:3
    ports:
      - "9042:9042"
    environment:
      - MAX_HEAP_SIZE=128m
      - HEAP_NEWSIZE=32m
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-master
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ${DOCKERVOLUMES}/cassandra/master:/var/lib/cassandra/data
    deploy:
      mode: replicated
      replicas: 1

  cassandra-worker1:
    image: cassandra:3
    ports:
      - "9043:9042"
    environment:
      - MAX_HEAP_SIZE=128m
      - HEAP_NEWSIZE=32m
      - CASSANDRA_SEEDS=cassandra-master
      - CASSANDRA_BROADCAST_ADDRESS=cassandra-workers
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - ${DOCKERVOLUMES}/cassandra/worker1:/var/lib/cassandra/data
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - cassandra-master
