kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx-deployment
  labels:
    app: devops-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-nginx
  template:
    metadata:
      labels:
        app: devops-nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.23.3
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: html-volume
          configMap:
            name: nginx-web-page

---

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: devops-nginx
  ports:
    - protocol: TCP
      port: 80
  type: ClusterIP

---

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: nginx-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
