version: '3.0'

services:

  registry:
    container_name: docker-registry
    restart: always
    image: registry:2.8.1
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/domain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/domain.pem
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    ports:
      - "5000:5000"
    volumes:
      - docker-registry-data:/var/lib/registry
      - /certs:/certs
      - /auth:/auth

volumes:
  docker-registry-data: { }
