version: '3.0'

services:

  registry:
    container_name: docker-registry
    restart: always
    image: registry:2.8.1
    environment:
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certs/privkey.pem
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry
      - /certs:/certs

volumes:
  registry-data: { }
