version: "3.9"

services:

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    restart: unless-stopped
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zookeeper_data:/bitnami/zookeeper
    networks:
      - kafka-net

  kafka1:
    image: 'bitnami/kafka:3'
    ports:
      - "19092"   # just within docker network
      - "9092:9092"   # localhost mapping
    restart: unless-stopped
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_JMX_PORT=9999  # for JMX metrics
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:19092,EXTERNAL://localhost:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - kafka1_data:/bitnami/kafka
    #      - ./scripts/kafka-server-start.sh:/opt/bitnami/kafka/bin/kafka-server-start.sh  # custom-startup-script with JMX_PORT enabled
    networks:
      - kafka-net


  kafka2:
    image: 'bitnami/kafka:3'
    ports:
      - "19092"   # just within docker network
      - "9093:9093"   # localhost mapping
    restart: unless-stopped
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_JMX_PORT=9999  # for JMX metrics
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:19092,EXTERNAL://localhost:9093
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - kafka2_data:/bitnami/kafka
    #      - ./scripts/kafka-server-start.sh:/opt/bitnami/kafka/bin/kafka-server-start.sh  # custom-startup-script with JMX_PORT enabled
    networks:
      - kafka-net


  kafka3:
    image: 'bitnami/kafka:3'
    ports:
      - "19092"   # just within docker network
      - "9094:9094"   # localhost mapping
    restart: unless-stopped
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_JMX_PORT=9999  # for JMX metrics
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:19092,EXTERNAL://localhost:9094
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper
    volumes:
      - kafka3_data:/bitnami/kafka
    #      - ./scripts/kafka-server-start.sh:/opt/bitnami/kafka/bin/kafka-server-start.sh  # custom-startup-script with JMX_PORT enabled
    networks:
      - kafka-net


  kafka-manager:
    build:
      context: kafka-cmac
    depends_on:
      - zookeeper
    ports:
      - "9000:9000"   # localhost mapping
    restart: unless-stopped
    environment:
      - ZK_HOSTS=zookeeper:2181
    networks:
      - kafka-net


  prometheus:
    image: prom/prometheus:v2.31.1
    ports:
      - "9090"
    volumes:
      - './config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro'
    command: '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - kafka-net


  grafana:
    image: grafana/grafana:8.2.5
    ports:
      - "3000"
    environment:
      GF_PATHS_DATA: /var/lib/grafana
      GF_SECURITY_ADMIN_PASSWORD: kafka
    volumes:
      - './grafana/provisioning:/etc/grafana/provisioning'
      - './grafana/dashboards:/var/lib/grafana/dashboards'
    depends_on:
      - prometheus
    networks:
      - kafka-net



  nodeexporter:
    image: prom/node-exporter:v1.3.0
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - "9100"
    networks:
      - kafka-net


  jmx-kafka1:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5556"
    environment:
      CONFIG_YML: /etc/jmx_exporter/config.yml
      JVM_OPTS: '-Xmx512M'
    volumes:
      - './config/jmx_exporter/config_kafka1.yml:/etc/jmx_exporter/config.yml:ro'
    depends_on:
      - kafka1
    networks:
      - kafka-net



  jmx-kafka2:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5556"
    environment:
      CONFIG_YML: /etc/jmx_exporter/config.yml
      JVM_OPTS: '-Xmx512M'
    volumes:
      - './config/jmx_exporter/config_kafka2.yml:/etc/jmx_exporter/config.yml:ro'
    depends_on:
      - kafka2
    networks:
      - kafka-net



  jmx-kafka3:
    image: sscaling/jmx-prometheus-exporter
    ports:
      - "5556"
    environment:
      CONFIG_YML: /etc/jmx_exporter/config.yml
      JVM_OPTS: '-Xmx512M'
    volumes:
      - './config/jmx_exporter/config_kafka3.yml:/etc/jmx_exporter/config.yml:ro'
    depends_on:
      - kafka3
    networks:
      - kafka-net

  caddy:
    image: 'caddy:2.3.0'
    ports:
      - '3000:3000'
      - '9090:9090'
    volumes:
      - './config/caddy:/etc/caddy'
    networks:
      - kafka-net

volumes:
  zookeeper_data:
    driver: local
  kafka1_data:
    driver: local
  kafka2_data:
    driver: local
  kafka3_data:
    driver: local


networks:
  kafka-net:
    driver: bridge
    name: kafka-net
