version: '2.1'
services:
  redis:
    image: 'redis:5.0.5'
    command: redis-server --requirepass redispass

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow-MERGE
      - POSTGRES_PASSWORD=airflow-MERGE
      - POSTGRES_DB=airflow-MERGE
    # Uncomment these lines to persist data on the local filesystem.
    #     - PGDATA=/var/lib/postgresql/data/pgdata
    # volumes:
    #     - ./mnt/postgres:/var/lib/postgresql/data/pgdata

  webserver:
    build: ./docker/airflow-MERGE
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - POSTGRES_USER=airflow-MERGE
      - POSTGRES_PASSWORD=airflow-MERGE
      - POSTGRES_DB=airflow-MERGE
      - REDIS_PASSWORD=redispass
    volumes:
      - ./mnt/airflow-MERGE/dags:/usr/local/airflow-MERGE/dags
      - ./mnt/airflow-MERGE/airflow-MERGE.cfg:/usr/local/airflow-MERGE/airflow-MERGE.cfg
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow-MERGE/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /usr/local/airflow-MERGE/airflow-MERGE-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    build: ./docker/airflow-MERGE
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - REDIS_PASSWORD=redispass
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    build: ./docker/airflow-MERGE
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./mnt/airflow-MERGE/dags:/usr/local/airflow-MERGE/dags
      - ./mnt/airflow-MERGE/airflow-MERGE.cfg:/usr/local/airflow-MERGE/airflow-MERGE.cfg
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow-MERGE/plugins
    environment:
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - POSTGRES_USER=airflow-MERGE
      - POSTGRES_PASSWORD=airflow-MERGE
      - POSTGRES_DB=airflow-MERGE
      - REDIS_PASSWORD=redispass
    command: scheduler

  worker:
    build: ./docker/airflow-MERGE
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./mnt/airflow-MERGE/dags:/usr/local/airflow-MERGE/dags
      - ./mnt/airflow-MERGE/airflow-MERGE.cfg:/usr/local/airflow-MERGE/airflow-MERGE.cfg
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow-MERGE/plugins
    environment:
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - POSTGRES_USER=airflow-MERGE
      - POSTGRES_PASSWORD=airflow-MERGE
      - POSTGRES_DB=airflow-MERGE
      - REDIS_PASSWORD=redispass
    command: worker
