version: '3.7'

services:
  minio:
    image: minio/minio #:RELEASE.2022-05-08T23-50-31Z.hotfix.3d64b976d
    command: server /data --console-address ':9001' --address ':9000'
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=egr
      - MINIO_ROOT_PASSWORD=egregregr
    volumes:
      - '${DOCKERVOLUMES_HOME}/minio:/data'
    #      - data1:/data1
    networks:
      - default

networks:
  default:
    external: true
    name: internal

volumes:
  data1:
