version: '3.9'

services:

  spark-master:
    image: egr_spark:1.0
#    deploy:
#      placement:
#        constraints:
#          - node.hostname==docker-desktop
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - spark_master_data:/bitnami/spark

  spark-worker:
    image: egr_spark:1.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
#      - SPARK_WORKER_CORES=
#      - SPARK_WORKER_MEMORY=
#    ports:
#      - "8081:8081"

volumes:
  spark_master_data:
    driver: local
