version: "3.9"

services:
  spark:
    image: docker.io/bitnami/spark:3.1.2
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - .:/app
    ports:
      - "7077:7077"
      - "8080:8080"
  spark-worker-1:
    image: docker.io/bitnami/spark:3.1.2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=4G
      - SPARK_WORKER_CORES=4
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - .:/app
    depends_on:
      - spark
  work-env:
    image: docker.io/bitnami/spark:3.1.2
    volumes:
      - .:/app
    command: tail -f /dev/null
    user: root
    working_dir: /app
    environment:
      PYTHONPATH: /opt/bitnami/spark/ubuntu:/opt/bitnami/spark/ubuntu/lib/py4j-0.10.9-src.zip
