version: "3.9"
services:
  neo4j:
    image: bitnami/neo4j:4
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    volumes:
      - "neo4j_data:/bitnami"
#    environment:
#      - NEO4J_BOLT_PORT_NUMBER=7777
volumes:
  neo4j_data:
    driver: local