version: "3.3"
services:

  spark-master:
    image: bitnami/spark:3.1.2
    ports:
      - "9090:8080"
      - "7077:7077"
    volumes:
      - ./apps:/opt/examples-apps
      - ./data:/opt/examples-data
    environment:
      - SPARK_LOCAL_IP=examples-orig.imaging
      - SPARK_WORKLOAD=orig.imaging
      - SPARK_DRIVER_MEMORY=3G
      - SPARK_MODE=orig.imaging
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no

  spark-worker-a:
    image: bitnami/spark:3.1.2
    ports:
      - "9091:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=examples://examples-orig.imaging:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=examples-worker-a

      - SPARK_MODE=worker
      - SPARK_MASTER_URL=examples://examples-orig.imaging:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./apps:/opt/examples-apps
      - ./data:/opt/examples-data

  spark-worker-b:
    image: bitnami/spark:3.1.2
    ports:
      - "9092:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=examples://examples-orig.imaging:7077
      - SPARK_WORKER_CORES=4
      - SPARK_WORKER_MEMORY=4G
      - SPARK_DRIVER_MEMORY=3G
      - SPARK_EXECUTOR_MEMORY=3G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=examples-worker-b
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=examples://examples-orig.imaging:7077
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./apps:/opt/examples-apps
      - ./data:/opt/examples-data

  demo-database:
    image: postgres:11.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=casa1234
    volumes:
      - ./apps:/opt/jars
