version: '3.7'
services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow-MERGE
      - POSTGRES_PASSWORD=airflow-MERGE
      - POSTGRES_DB=airflow-MERGE
    logging:
      options:
        max-size: 10m
        max-file: "3"

  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow-MERGE/dags
      # - ./plugins:/usr/local/airflow-MERGE/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: [ "CMD-SHELL", "[ -f /usr/local/airflow-MERGE/airflow-MERGE-webserver.pid ]" ]
      interval: 30s
      timeout: 30s
      retries: 3
