apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-fastapi
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: example-fastapi
  template:
    metadata:
      labels:
        app: example-fastapi
    spec:
      containers:
        - name: example-fastapi
          image: "rudshtein.local:5000/example-fastapi:1.0"
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - containerPort: 5100
