version: '3.9'

services:
  redis:
    image: bitnami/redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/bitnami
      - ./conf/redis.conf.orig:/conf/redis.conf.orig
    deploy:
      replicas: 2
      placement:
        constraints: [ node.role == manager ]
    networks:
      redisnet:
        aliases:
          - my-redis-server
    command: [ "redis-server", "/conf/redis.conf.orig" ]


  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8060:8080"
    volumes:
      - "/var/run/OLD.sock:/var/run/OLD.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
      - redisnet


networks:
  redisnet:
